// Code generated by pkg/localization/internal/proceduremetadata; DO NOT EDIT.

package localization

const (
	MessageCypherProcedureMetadataDbAwaitIndex                                  MessageID = "cypherproceduremetadata.db_awaitindex"
	MessageCypherProcedureMetadataDbAwaitIndexes                                MessageID = "cypherproceduremetadata.db_awaitindexes"
	MessageCypherProcedureMetadataDbClearQueryCaches                            MessageID = "cypherproceduremetadata.db_clearquerycaches"
	MessageCypherProcedureMetadataDbConstraints                                 MessageID = "cypherproceduremetadata.db_constraints"
	MessageCypherProcedureMetadataDbCreateSetNodeVectorProperty                 MessageID = "cypherproceduremetadata.db_create_setnodevectorproperty"
	MessageCypherProcedureMetadataDbCreateSetRelationshipVectorProperty         MessageID = "cypherproceduremetadata.db_create_setrelationshipvectorproperty"
	MessageCypherProcedureMetadataDbIndexFulltextCreateNodeIndex                MessageID = "cypherproceduremetadata.db_index_fulltext_createnodeindex"
	MessageCypherProcedureMetadataDbIndexFulltextCreateRelationshipIndex        MessageID = "cypherproceduremetadata.db_index_fulltext_createrelationshipindex"
	MessageCypherProcedureMetadataDbIndexFulltextDrop                           MessageID = "cypherproceduremetadata.db_index_fulltext_drop"
	MessageCypherProcedureMetadataDbIndexFulltextListAvailableAnalyzers         MessageID = "cypherproceduremetadata.db_index_fulltext_listavailableanalyzers"
	MessageCypherProcedureMetadataDbIndexFulltextQueryNodes                     MessageID = "cypherproceduremetadata.db_index_fulltext_querynodes"
	MessageCypherProcedureMetadataDbIndexFulltextQueryRelationships             MessageID = "cypherproceduremetadata.db_index_fulltext_queryrelationships"
	MessageCypherProcedureMetadataDbIndexStats                                  MessageID = "cypherproceduremetadata.db_index_stats"
	MessageCypherProcedureMetadataDbIndexVectorCreateNodeIndex                  MessageID = "cypherproceduremetadata.db_index_vector_createnodeindex"
	MessageCypherProcedureMetadataDbIndexVectorCreateRelationshipIndex          MessageID = "cypherproceduremetadata.db_index_vector_createrelationshipindex"
	MessageCypherProcedureMetadataDbIndexVectorDrop                             MessageID = "cypherproceduremetadata.db_index_vector_drop"
	MessageCypherProcedureMetadataDbIndexVectorEmbed                            MessageID = "cypherproceduremetadata.db_index_vector_embed"
	MessageCypherProcedureMetadataDbIndexVectorQueryNodes                       MessageID = "cypherproceduremetadata.db_index_vector_querynodes"
	MessageCypherProcedureMetadataDbIndexVectorQueryRelationships               MessageID = "cypherproceduremetadata.db_index_vector_queryrelationships"
	MessageCypherProcedureMetadataDbIndexes                                     MessageID = "cypherproceduremetadata.db_indexes"
	MessageCypherProcedureMetadataDbInfer                                       MessageID = "cypherproceduremetadata.db_infer"
	MessageCypherProcedureMetadataDbInfo                                        MessageID = "cypherproceduremetadata.db_info"
	MessageCypherProcedureMetadataDbLabels                                      MessageID = "cypherproceduremetadata.db_labels"
	MessageCypherProcedureMetadataDbPing                                        MessageID = "cypherproceduremetadata.db_ping"
	MessageCypherProcedureMetadataDbPropertyKeys                                MessageID = "cypherproceduremetadata.db_propertykeys"
	MessageCypherProcedureMetadataDbRelationshipTypes                           MessageID = "cypherproceduremetadata.db_relationshiptypes"
	MessageCypherProcedureMetadataDbRerank                                      MessageID = "cypherproceduremetadata.db_rerank"
	MessageCypherProcedureMetadataDbResampleIndex                               MessageID = "cypherproceduremetadata.db_resampleindex"
	MessageCypherProcedureMetadataDbRetrieve                                    MessageID = "cypherproceduremetadata.db_retrieve"
	MessageCypherProcedureMetadataDbRretrieve                                   MessageID = "cypherproceduremetadata.db_rretrieve"
	MessageCypherProcedureMetadataDbSchemaNodeProperties                        MessageID = "cypherproceduremetadata.db_schema_nodeproperties"
	MessageCypherProcedureMetadataDbSchemaRelProperties                         MessageID = "cypherproceduremetadata.db_schema_relproperties"
	MessageCypherProcedureMetadataDbSchemaVisualization                         MessageID = "cypherproceduremetadata.db_schema_visualization"
	MessageCypherProcedureMetadataDbStatsClear                                  MessageID = "cypherproceduremetadata.db_stats_clear"
	MessageCypherProcedureMetadataDbStatsCollect                                MessageID = "cypherproceduremetadata.db_stats_collect"
	MessageCypherProcedureMetadataDbStatsRetrieve                               MessageID = "cypherproceduremetadata.db_stats_retrieve"
	MessageCypherProcedureMetadataDbStatsRetrieveAllAnTheStats                  MessageID = "cypherproceduremetadata.db_stats_retrieveallanthestats"
	MessageCypherProcedureMetadataDbStatsStatus                                 MessageID = "cypherproceduremetadata.db_stats_status"
	MessageCypherProcedureMetadataDbStatsStop                                   MessageID = "cypherproceduremetadata.db_stats_stop"
	MessageCypherProcedureMetadataDbTemporalAsOf                                MessageID = "cypherproceduremetadata.db_temporal_asof"
	MessageCypherProcedureMetadataDbTemporalAssertNoOverlap                     MessageID = "cypherproceduremetadata.db_temporal_assertnooverlap"
	MessageCypherProcedureMetadataDbTxlogByTxId                                 MessageID = "cypherproceduremetadata.db_txlog_bytxid"
	MessageCypherProcedureMetadataDbTxlogEntries                                MessageID = "cypherproceduremetadata.db_txlog_entries"
	MessageCypherProcedureMetadataDbmsClientConfig                              MessageID = "cypherproceduremetadata.dbms_clientconfig"
	MessageCypherProcedureMetadataDbmsComponents                                MessageID = "cypherproceduremetadata.dbms_components"
	MessageCypherProcedureMetadataDbmsFunctions                                 MessageID = "cypherproceduremetadata.dbms_functions"
	MessageCypherProcedureMetadataDbmsInfo                                      MessageID = "cypherproceduremetadata.dbms_info"
	MessageCypherProcedureMetadataDbmsListConfig                                MessageID = "cypherproceduremetadata.dbms_listconfig"
	MessageCypherProcedureMetadataDbmsListConnections                           MessageID = "cypherproceduremetadata.dbms_listconnections"
	MessageCypherProcedureMetadataDbmsProcedures                                MessageID = "cypherproceduremetadata.dbms_procedures"
	MessageCypherProcedureMetadataGdsFastRPStats                                MessageID = "cypherproceduremetadata.gds_fastrp_stats"
	MessageCypherProcedureMetadataGdsFastRPStream                               MessageID = "cypherproceduremetadata.gds_fastrp_stream"
	MessageCypherProcedureMetadataGdsGraphDrop                                  MessageID = "cypherproceduremetadata.gds_graph_drop"
	MessageCypherProcedureMetadataGdsGraphList                                  MessageID = "cypherproceduremetadata.gds_graph_list"
	MessageCypherProcedureMetadataGdsGraphProject                               MessageID = "cypherproceduremetadata.gds_graph_project"
	MessageCypherProcedureMetadataGdsLinkPredictionAdamicAdarStream             MessageID = "cypherproceduremetadata.gds_linkprediction_adamicadar_stream"
	MessageCypherProcedureMetadataGdsLinkPredictionCommonNeighborsStream        MessageID = "cypherproceduremetadata.gds_linkprediction_commonneighbors_stream"
	MessageCypherProcedureMetadataGdsLinkPredictionJaccardStream                MessageID = "cypherproceduremetadata.gds_linkprediction_jaccard_stream"
	MessageCypherProcedureMetadataGdsLinkPredictionPredictStream                MessageID = "cypherproceduremetadata.gds_linkprediction_predict_stream"
	MessageCypherProcedureMetadataGdsLinkPredictionPreferentialAttachmentStream MessageID = "cypherproceduremetadata.gds_linkprediction_preferentialattachment_stream"
	MessageCypherProcedureMetadataGdsLinkPredictionResourceAllocationStream     MessageID = "cypherproceduremetadata.gds_linkprediction_resourceallocation_stream"
	MessageCypherProcedureMetadataGdsVersion                                    MessageID = "cypherproceduremetadata.gds_version"
	MessageCypherProcedureMetadataNornicdbDecayInfo                             MessageID = "cypherproceduremetadata.nornicdb_decay_info"
	MessageCypherProcedureMetadataNornicdbKnowledgepolicyDeindexStatus          MessageID = "cypherproceduremetadata.nornicdb_knowledgepolicy_deindexstatus"
	MessageCypherProcedureMetadataNornicdbKnowledgepolicyInfo                   MessageID = "cypherproceduremetadata.nornicdb_knowledgepolicy_info"
	MessageCypherProcedureMetadataNornicdbKnowledgepolicyPolicies               MessageID = "cypherproceduremetadata.nornicdb_knowledgepolicy_policies"
	MessageCypherProcedureMetadataNornicdbKnowledgepolicyProfiles               MessageID = "cypherproceduremetadata.nornicdb_knowledgepolicy_profiles"
	MessageCypherProcedureMetadataNornicdbKnowledgepolicyResolve                MessageID = "cypherproceduremetadata.nornicdb_knowledgepolicy_resolve"
	MessageCypherProcedureMetadataNornicdbStats                                 MessageID = "cypherproceduremetadata.nornicdb_stats"
	MessageCypherProcedureMetadataNornicdbVersion                               MessageID = "cypherproceduremetadata.nornicdb_version"
	MessageCypherProcedureMetadataTxSetMetaData                                 MessageID = "cypherproceduremetadata.tx_setmetadata"
)

// CypherProcedureMetadataDbAwaitIndex describes db.awaitIndex in procedure listings.
func CypherProcedureMetadataDbAwaitIndex() Message {
	return Message{ID: MessageCypherProcedureMetadataDbAwaitIndex, Fallback: "Waits for one index to be online"}
}

// CypherProcedureMetadataDbAwaitIndexes describes db.awaitIndexes in procedure listings.
func CypherProcedureMetadataDbAwaitIndexes() Message {
	return Message{ID: MessageCypherProcedureMetadataDbAwaitIndexes, Fallback: "Waits for all indexes to be online"}
}

// CypherProcedureMetadataDbClearQueryCaches describes db.clearQueryCaches in procedure listings.
func CypherProcedureMetadataDbClearQueryCaches() Message {
	return Message{ID: MessageCypherProcedureMetadataDbClearQueryCaches, Fallback: "Clears query caches"}
}

// CypherProcedureMetadataDbConstraints describes db.constraints in procedure listings.
func CypherProcedureMetadataDbConstraints() Message {
	return Message{ID: MessageCypherProcedureMetadataDbConstraints, Fallback: "Lists all constraints in the database"}
}

// CypherProcedureMetadataDbCreateSetNodeVectorProperty describes db.create.setNodeVectorProperty in procedure listings.
func CypherProcedureMetadataDbCreateSetNodeVectorProperty() Message {
	return Message{ID: MessageCypherProcedureMetadataDbCreateSetNodeVectorProperty, Fallback: "Sets vector property on a node"}
}

// CypherProcedureMetadataDbCreateSetRelationshipVectorProperty describes db.create.setRelationshipVectorProperty in procedure listings.
func CypherProcedureMetadataDbCreateSetRelationshipVectorProperty() Message {
	return Message{ID: MessageCypherProcedureMetadataDbCreateSetRelationshipVectorProperty, Fallback: "Sets vector property on a relationship"}
}

// CypherProcedureMetadataDbIndexFulltextCreateNodeIndex describes db.index.fulltext.createNodeIndex in procedure listings.
func CypherProcedureMetadataDbIndexFulltextCreateNodeIndex() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexFulltextCreateNodeIndex, Fallback: "Creates fulltext index on nodes"}
}

// CypherProcedureMetadataDbIndexFulltextCreateRelationshipIndex describes db.index.fulltext.createRelationshipIndex in procedure listings.
func CypherProcedureMetadataDbIndexFulltextCreateRelationshipIndex() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexFulltextCreateRelationshipIndex, Fallback: "Creates fulltext index on relationships"}
}

// CypherProcedureMetadataDbIndexFulltextDrop describes db.index.fulltext.drop in procedure listings.
func CypherProcedureMetadataDbIndexFulltextDrop() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexFulltextDrop, Fallback: "Drops fulltext index"}
}

// CypherProcedureMetadataDbIndexFulltextListAvailableAnalyzers describes db.index.fulltext.listAvailableAnalyzers in procedure listings.
func CypherProcedureMetadataDbIndexFulltextListAvailableAnalyzers() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexFulltextListAvailableAnalyzers, Fallback: "Lists available analyzers"}
}

// CypherProcedureMetadataDbIndexFulltextQueryNodes describes db.index.fulltext.queryNodes in procedure listings.
func CypherProcedureMetadataDbIndexFulltextQueryNodes() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexFulltextQueryNodes, Fallback: "Fulltext search on nodes"}
}

// CypherProcedureMetadataDbIndexFulltextQueryRelationships describes db.index.fulltext.queryRelationships in procedure listings.
func CypherProcedureMetadataDbIndexFulltextQueryRelationships() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexFulltextQueryRelationships, Fallback: "Fulltext search on relationships"}
}

// CypherProcedureMetadataDbIndexStats describes db.index.stats in procedure listings.
func CypherProcedureMetadataDbIndexStats() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexStats, Fallback: "Returns index statistics"}
}

// CypherProcedureMetadataDbIndexVectorCreateNodeIndex describes db.index.vector.createNodeIndex in procedure listings.
func CypherProcedureMetadataDbIndexVectorCreateNodeIndex() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexVectorCreateNodeIndex, Fallback: "Creates vector index on nodes"}
}

// CypherProcedureMetadataDbIndexVectorCreateRelationshipIndex describes db.index.vector.createRelationshipIndex in procedure listings.
func CypherProcedureMetadataDbIndexVectorCreateRelationshipIndex() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexVectorCreateRelationshipIndex, Fallback: "Creates vector index on relationships"}
}

// CypherProcedureMetadataDbIndexVectorDrop describes db.index.vector.drop in procedure listings.
func CypherProcedureMetadataDbIndexVectorDrop() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexVectorDrop, Fallback: "Drops vector index"}
}

// CypherProcedureMetadataDbIndexVectorEmbed describes db.index.vector.embed in procedure listings.
func CypherProcedureMetadataDbIndexVectorEmbed() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexVectorEmbed, Fallback: "Embeds text using configured embedder"}
}

// CypherProcedureMetadataDbIndexVectorQueryNodes describes db.index.vector.queryNodes in procedure listings.
func CypherProcedureMetadataDbIndexVectorQueryNodes() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexVectorQueryNodes, Fallback: "Vector search on nodes"}
}

// CypherProcedureMetadataDbIndexVectorQueryRelationships describes db.index.vector.queryRelationships in procedure listings.
func CypherProcedureMetadataDbIndexVectorQueryRelationships() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexVectorQueryRelationships, Fallback: "Vector search on relationships"}
}

// CypherProcedureMetadataDbIndexes describes db.indexes in procedure listings.
func CypherProcedureMetadataDbIndexes() Message {
	return Message{ID: MessageCypherProcedureMetadataDbIndexes, Fallback: "Lists all indexes in the database"}
}

// CypherProcedureMetadataDbInfer describes db.infer in procedure listings.
func CypherProcedureMetadataDbInfer() Message {
	return Message{ID: MessageCypherProcedureMetadataDbInfer, Fallback: "LLM inference procedure"}
}

// CypherProcedureMetadataDbInfo describes db.info in procedure listings.
func CypherProcedureMetadataDbInfo() Message {
	return Message{ID: MessageCypherProcedureMetadataDbInfo, Fallback: "Returns database information"}
}

// CypherProcedureMetadataDbLabels describes db.labels in procedure listings.
func CypherProcedureMetadataDbLabels() Message {
	return Message{ID: MessageCypherProcedureMetadataDbLabels, Fallback: "Lists all labels in the database"}
}

// CypherProcedureMetadataDbPing describes db.ping in procedure listings.
func CypherProcedureMetadataDbPing() Message {
	return Message{ID: MessageCypherProcedureMetadataDbPing, Fallback: "Checks database connectivity"}
}

// CypherProcedureMetadataDbPropertyKeys describes db.propertyKeys in procedure listings.
func CypherProcedureMetadataDbPropertyKeys() Message {
	return Message{ID: MessageCypherProcedureMetadataDbPropertyKeys, Fallback: "Lists all property keys in the database"}
}

// CypherProcedureMetadataDbRelationshipTypes describes db.relationshipTypes in procedure listings.
func CypherProcedureMetadataDbRelationshipTypes() Message {
	return Message{ID: MessageCypherProcedureMetadataDbRelationshipTypes, Fallback: "Lists all relationship types in the database"}
}

// CypherProcedureMetadataDbRerank describes db.rerank in procedure listings.
func CypherProcedureMetadataDbRerank() Message {
	return Message{ID: MessageCypherProcedureMetadataDbRerank, Fallback: "Standalone rerank procedure"}
}

// CypherProcedureMetadataDbResampleIndex describes db.resampleIndex in procedure listings.
func CypherProcedureMetadataDbResampleIndex() Message {
	return Message{ID: MessageCypherProcedureMetadataDbResampleIndex, Fallback: "Resamples index statistics"}
}

// CypherProcedureMetadataDbRetrieve describes db.retrieve in procedure listings.
func CypherProcedureMetadataDbRetrieve() Message {
	return Message{ID: MessageCypherProcedureMetadataDbRetrieve, Fallback: "Hybrid retrieval procedure"}
}

// CypherProcedureMetadataDbRretrieve describes db.rretrieve in procedure listings.
func CypherProcedureMetadataDbRretrieve() Message {
	return Message{ID: MessageCypherProcedureMetadataDbRretrieve, Fallback: "Hybrid retrieval + rerank procedure"}
}

// CypherProcedureMetadataDbSchemaNodeProperties describes db.schema.nodeProperties in procedure listings.
func CypherProcedureMetadataDbSchemaNodeProperties() Message {
	return Message{ID: MessageCypherProcedureMetadataDbSchemaNodeProperties, Fallback: "Returns node properties by label"}
}

// CypherProcedureMetadataDbSchemaRelProperties describes db.schema.relProperties in procedure listings.
func CypherProcedureMetadataDbSchemaRelProperties() Message {
	return Message{ID: MessageCypherProcedureMetadataDbSchemaRelProperties, Fallback: "Returns relationship properties by type"}
}

// CypherProcedureMetadataDbSchemaVisualization describes db.schema.visualization in procedure listings.
func CypherProcedureMetadataDbSchemaVisualization() Message {
	return Message{ID: MessageCypherProcedureMetadataDbSchemaVisualization, Fallback: "Visualizes schema"}
}

// CypherProcedureMetadataDbStatsClear describes db.stats.clear in procedure listings.
func CypherProcedureMetadataDbStatsClear() Message {
	return Message{ID: MessageCypherProcedureMetadataDbStatsClear, Fallback: "Clears collected statistics"}
}

// CypherProcedureMetadataDbStatsCollect describes db.stats.collect in procedure listings.
func CypherProcedureMetadataDbStatsCollect() Message {
	return Message{ID: MessageCypherProcedureMetadataDbStatsCollect, Fallback: "Starts statistics collection"}
}

// CypherProcedureMetadataDbStatsRetrieve describes db.stats.retrieve in procedure listings.
func CypherProcedureMetadataDbStatsRetrieve() Message {
	return Message{ID: MessageCypherProcedureMetadataDbStatsRetrieve, Fallback: "Retrieves collected statistics"}
}

// CypherProcedureMetadataDbStatsRetrieveAllAnTheStats describes db.stats.retrieveAllAnTheStats in procedure listings.
func CypherProcedureMetadataDbStatsRetrieveAllAnTheStats() Message {
	return Message{ID: MessageCypherProcedureMetadataDbStatsRetrieveAllAnTheStats, Fallback: "Retrieves all statistics"}
}

// CypherProcedureMetadataDbStatsStatus describes db.stats.status in procedure listings.
func CypherProcedureMetadataDbStatsStatus() Message {
	return Message{ID: MessageCypherProcedureMetadataDbStatsStatus, Fallback: "Returns statistics collection status"}
}

// CypherProcedureMetadataDbStatsStop describes db.stats.stop in procedure listings.
func CypherProcedureMetadataDbStatsStop() Message {
	return Message{ID: MessageCypherProcedureMetadataDbStatsStop, Fallback: "Stops statistics collection"}
}

// CypherProcedureMetadataDbTemporalAsOf describes db.temporal.asOf in procedure listings.
func CypherProcedureMetadataDbTemporalAsOf() Message {
	return Message{ID: MessageCypherProcedureMetadataDbTemporalAsOf, Fallback: "Reads temporal graph at point in time"}
}

// CypherProcedureMetadataDbTemporalAssertNoOverlap describes db.temporal.assertNoOverlap in procedure listings.
func CypherProcedureMetadataDbTemporalAssertNoOverlap() Message {
	return Message{ID: MessageCypherProcedureMetadataDbTemporalAssertNoOverlap, Fallback: "Checks temporal overlap constraints"}
}

// CypherProcedureMetadataDbTxlogByTxId describes db.txlog.byTxId in procedure listings.
func CypherProcedureMetadataDbTxlogByTxId() Message {
	return Message{ID: MessageCypherProcedureMetadataDbTxlogByTxId, Fallback: "Returns WAL entries for a transaction id"}
}

// CypherProcedureMetadataDbTxlogEntries describes db.txlog.entries in procedure listings.
func CypherProcedureMetadataDbTxlogEntries() Message {
	return Message{ID: MessageCypherProcedureMetadataDbTxlogEntries, Fallback: "Returns transaction log entries"}
}

// CypherProcedureMetadataDbmsClientConfig describes dbms.clientConfig in procedure listings.
func CypherProcedureMetadataDbmsClientConfig() Message {
	return Message{ID: MessageCypherProcedureMetadataDbmsClientConfig, Fallback: "Returns client config"}
}

// CypherProcedureMetadataDbmsComponents describes dbms.components in procedure listings.
func CypherProcedureMetadataDbmsComponents() Message {
	return Message{ID: MessageCypherProcedureMetadataDbmsComponents, Fallback: "Lists DBMS components"}
}

// CypherProcedureMetadataDbmsFunctions describes dbms.functions in procedure listings.
func CypherProcedureMetadataDbmsFunctions() Message {
	return Message{ID: MessageCypherProcedureMetadataDbmsFunctions, Fallback: "Lists functions"}
}

// CypherProcedureMetadataDbmsInfo describes dbms.info in procedure listings.
func CypherProcedureMetadataDbmsInfo() Message {
	return Message{ID: MessageCypherProcedureMetadataDbmsInfo, Fallback: "Returns DBMS information"}
}

// CypherProcedureMetadataDbmsListConfig describes dbms.listConfig in procedure listings.
func CypherProcedureMetadataDbmsListConfig() Message {
	return Message{ID: MessageCypherProcedureMetadataDbmsListConfig, Fallback: "Lists DBMS configuration"}
}

// CypherProcedureMetadataDbmsListConnections describes dbms.listConnections in procedure listings.
func CypherProcedureMetadataDbmsListConnections() Message {
	return Message{ID: MessageCypherProcedureMetadataDbmsListConnections, Fallback: "Lists active DBMS connections"}
}

// CypherProcedureMetadataDbmsProcedures describes dbms.procedures in procedure listings.
func CypherProcedureMetadataDbmsProcedures() Message {
	return Message{ID: MessageCypherProcedureMetadataDbmsProcedures, Fallback: "Lists procedures"}
}

// CypherProcedureMetadataGdsFastRPStats describes gds.fastRP.stats in procedure listings.
func CypherProcedureMetadataGdsFastRPStats() Message {
	return Message{ID: MessageCypherProcedureMetadataGdsFastRPStats, Fallback: "Runs FastRP and returns statistics"}
}

// CypherProcedureMetadataGdsFastRPStream describes gds.fastRP.stream in procedure listings.
func CypherProcedureMetadataGdsFastRPStream() Message {
	return Message{ID: MessageCypherProcedureMetadataGdsFastRPStream, Fallback: "Streams FastRP embeddings"}
}

// CypherProcedureMetadataGdsGraphDrop describes gds.graph.drop in procedure listings.
func CypherProcedureMetadataGdsGraphDrop() Message {
	return Message{ID: MessageCypherProcedureMetadataGdsGraphDrop, Fallback: "Drops projected GDS graph"}
}

// CypherProcedureMetadataGdsGraphList describes gds.graph.list in procedure listings.
func CypherProcedureMetadataGdsGraphList() Message {
	return Message{ID: MessageCypherProcedureMetadataGdsGraphList, Fallback: "Lists projected GDS graphs"}
}

// CypherProcedureMetadataGdsGraphProject describes gds.graph.project in procedure listings.
func CypherProcedureMetadataGdsGraphProject() Message {
	return Message{ID: MessageCypherProcedureMetadataGdsGraphProject, Fallback: "Projects graph into GDS catalog"}
}

// CypherProcedureMetadataGdsLinkPredictionAdamicAdarStream describes gds.linkPrediction.adamicAdar.stream in procedure listings.
func CypherProcedureMetadataGdsLinkPredictionAdamicAdarStream() Message {
	return Message{ID: MessageCypherProcedureMetadataGdsLinkPredictionAdamicAdarStream, Fallback: "Runs Adamic-Adar link prediction"}
}

// CypherProcedureMetadataGdsLinkPredictionCommonNeighborsStream describes gds.linkPrediction.commonNeighbors.stream in procedure listings.
func CypherProcedureMetadataGdsLinkPredictionCommonNeighborsStream() Message {
	return Message{ID: MessageCypherProcedureMetadataGdsLinkPredictionCommonNeighborsStream, Fallback: "Runs common neighbors link prediction"}
}

// CypherProcedureMetadataGdsLinkPredictionJaccardStream describes gds.linkPrediction.jaccard.stream in procedure listings.
func CypherProcedureMetadataGdsLinkPredictionJaccardStream() Message {
	return Message{ID: MessageCypherProcedureMetadataGdsLinkPredictionJaccardStream, Fallback: "Runs Jaccard link prediction"}
}

// CypherProcedureMetadataGdsLinkPredictionPredictStream describes gds.linkPrediction.predict.stream in procedure listings.
func CypherProcedureMetadataGdsLinkPredictionPredictStream() Message {
	return Message{ID: MessageCypherProcedureMetadataGdsLinkPredictionPredictStream, Fallback: "Runs model-based link prediction"}
}

// CypherProcedureMetadataGdsLinkPredictionPreferentialAttachmentStream describes gds.linkPrediction.preferentialAttachment.stream in procedure listings.
func CypherProcedureMetadataGdsLinkPredictionPreferentialAttachmentStream() Message {
	return Message{ID: MessageCypherProcedureMetadataGdsLinkPredictionPreferentialAttachmentStream, Fallback: "Runs preferential attachment link prediction"}
}

// CypherProcedureMetadataGdsLinkPredictionResourceAllocationStream describes gds.linkPrediction.resourceAllocation.stream in procedure listings.
func CypherProcedureMetadataGdsLinkPredictionResourceAllocationStream() Message {
	return Message{ID: MessageCypherProcedureMetadataGdsLinkPredictionResourceAllocationStream, Fallback: "Runs resource-allocation link prediction"}
}

// CypherProcedureMetadataGdsVersion describes gds.version in procedure listings.
func CypherProcedureMetadataGdsVersion() Message {
	return Message{ID: MessageCypherProcedureMetadataGdsVersion, Fallback: "Returns GDS version"}
}

// CypherProcedureMetadataNornicdbDecayInfo describes nornicdb.decay.info in procedure listings.
func CypherProcedureMetadataNornicdbDecayInfo() Message {
	return Message{ID: MessageCypherProcedureMetadataNornicdbDecayInfo, Fallback: "Returns knowledge-layer scoring configuration"}
}

// CypherProcedureMetadataNornicdbKnowledgepolicyDeindexStatus describes nornicdb.knowledgepolicy.deindexStatus in procedure listings.
func CypherProcedureMetadataNornicdbKnowledgepolicyDeindexStatus() Message {
	return Message{ID: MessageCypherProcedureMetadataNornicdbKnowledgepolicyDeindexStatus, Fallback: "Returns knowledge-layer deindex queue status"}
}

// CypherProcedureMetadataNornicdbKnowledgepolicyInfo describes nornicdb.knowledgepolicy.info in procedure listings.
func CypherProcedureMetadataNornicdbKnowledgepolicyInfo() Message {
	return Message{ID: MessageCypherProcedureMetadataNornicdbKnowledgepolicyInfo, Fallback: "Returns knowledge-layer profile and policy catalog counts"}
}

// CypherProcedureMetadataNornicdbKnowledgepolicyPolicies describes nornicdb.knowledgepolicy.policies in procedure listings.
func CypherProcedureMetadataNornicdbKnowledgepolicyPolicies() Message {
	return Message{ID: MessageCypherProcedureMetadataNornicdbKnowledgepolicyPolicies, Fallback: "Returns knowledge-layer promotion profiles and policies"}
}

// CypherProcedureMetadataNornicdbKnowledgepolicyProfiles describes nornicdb.knowledgepolicy.profiles in procedure listings.
func CypherProcedureMetadataNornicdbKnowledgepolicyProfiles() Message {
	return Message{ID: MessageCypherProcedureMetadataNornicdbKnowledgepolicyProfiles, Fallback: "Returns knowledge-layer decay bundles and bindings"}
}

// CypherProcedureMetadataNornicdbKnowledgepolicyResolve describes nornicdb.knowledgepolicy.resolve in procedure listings.
func CypherProcedureMetadataNornicdbKnowledgepolicyResolve() Message {
	return Message{ID: MessageCypherProcedureMetadataNornicdbKnowledgepolicyResolve, Fallback: "Resolves the effective knowledge-layer scoring policy for an entity, label set, or edge type"}
}

// CypherProcedureMetadataNornicdbStats describes nornicdb.stats in procedure listings.
func CypherProcedureMetadataNornicdbStats() Message {
	return Message{ID: MessageCypherProcedureMetadataNornicdbStats, Fallback: "Returns NornicDB stats"}
}

// CypherProcedureMetadataNornicdbVersion describes nornicdb.version in procedure listings.
func CypherProcedureMetadataNornicdbVersion() Message {
	return Message{ID: MessageCypherProcedureMetadataNornicdbVersion, Fallback: "Returns NornicDB version"}
}

// CypherProcedureMetadataTxSetMetaData describes tx.setMetaData in procedure listings.
func CypherProcedureMetadataTxSetMetaData() Message {
	return Message{ID: MessageCypherProcedureMetadataTxSetMetaData, Fallback: "Sets transaction metadata"}
}

var cypherProcedureMetadata = map[string]func() Message{
	"db.awaitIndex":                                    CypherProcedureMetadataDbAwaitIndex,
	"db.awaitIndexes":                                  CypherProcedureMetadataDbAwaitIndexes,
	"db.clearQueryCaches":                              CypherProcedureMetadataDbClearQueryCaches,
	"db.constraints":                                   CypherProcedureMetadataDbConstraints,
	"db.create.setNodeVectorProperty":                  CypherProcedureMetadataDbCreateSetNodeVectorProperty,
	"db.create.setRelationshipVectorProperty":          CypherProcedureMetadataDbCreateSetRelationshipVectorProperty,
	"db.index.fulltext.createNodeIndex":                CypherProcedureMetadataDbIndexFulltextCreateNodeIndex,
	"db.index.fulltext.createRelationshipIndex":        CypherProcedureMetadataDbIndexFulltextCreateRelationshipIndex,
	"db.index.fulltext.drop":                           CypherProcedureMetadataDbIndexFulltextDrop,
	"db.index.fulltext.listAvailableAnalyzers":         CypherProcedureMetadataDbIndexFulltextListAvailableAnalyzers,
	"db.index.fulltext.queryNodes":                     CypherProcedureMetadataDbIndexFulltextQueryNodes,
	"db.index.fulltext.queryRelationships":             CypherProcedureMetadataDbIndexFulltextQueryRelationships,
	"db.index.stats":                                   CypherProcedureMetadataDbIndexStats,
	"db.index.vector.createNodeIndex":                  CypherProcedureMetadataDbIndexVectorCreateNodeIndex,
	"db.index.vector.createRelationshipIndex":          CypherProcedureMetadataDbIndexVectorCreateRelationshipIndex,
	"db.index.vector.drop":                             CypherProcedureMetadataDbIndexVectorDrop,
	"db.index.vector.embed":                            CypherProcedureMetadataDbIndexVectorEmbed,
	"db.index.vector.queryNodes":                       CypherProcedureMetadataDbIndexVectorQueryNodes,
	"db.index.vector.queryRelationships":               CypherProcedureMetadataDbIndexVectorQueryRelationships,
	"db.indexes":                                       CypherProcedureMetadataDbIndexes,
	"db.infer":                                         CypherProcedureMetadataDbInfer,
	"db.info":                                          CypherProcedureMetadataDbInfo,
	"db.labels":                                        CypherProcedureMetadataDbLabels,
	"db.ping":                                          CypherProcedureMetadataDbPing,
	"db.propertyKeys":                                  CypherProcedureMetadataDbPropertyKeys,
	"db.relationshipTypes":                             CypherProcedureMetadataDbRelationshipTypes,
	"db.rerank":                                        CypherProcedureMetadataDbRerank,
	"db.resampleIndex":                                 CypherProcedureMetadataDbResampleIndex,
	"db.retrieve":                                      CypherProcedureMetadataDbRetrieve,
	"db.rretrieve":                                     CypherProcedureMetadataDbRretrieve,
	"db.schema.nodeProperties":                         CypherProcedureMetadataDbSchemaNodeProperties,
	"db.schema.relProperties":                          CypherProcedureMetadataDbSchemaRelProperties,
	"db.schema.visualization":                          CypherProcedureMetadataDbSchemaVisualization,
	"db.stats.clear":                                   CypherProcedureMetadataDbStatsClear,
	"db.stats.collect":                                 CypherProcedureMetadataDbStatsCollect,
	"db.stats.retrieve":                                CypherProcedureMetadataDbStatsRetrieve,
	"db.stats.retrieveAllAnTheStats":                   CypherProcedureMetadataDbStatsRetrieveAllAnTheStats,
	"db.stats.status":                                  CypherProcedureMetadataDbStatsStatus,
	"db.stats.stop":                                    CypherProcedureMetadataDbStatsStop,
	"db.temporal.asOf":                                 CypherProcedureMetadataDbTemporalAsOf,
	"db.temporal.assertNoOverlap":                      CypherProcedureMetadataDbTemporalAssertNoOverlap,
	"db.txlog.byTxId":                                  CypherProcedureMetadataDbTxlogByTxId,
	"db.txlog.entries":                                 CypherProcedureMetadataDbTxlogEntries,
	"dbms.clientConfig":                                CypherProcedureMetadataDbmsClientConfig,
	"dbms.components":                                  CypherProcedureMetadataDbmsComponents,
	"dbms.functions":                                   CypherProcedureMetadataDbmsFunctions,
	"dbms.info":                                        CypherProcedureMetadataDbmsInfo,
	"dbms.listConfig":                                  CypherProcedureMetadataDbmsListConfig,
	"dbms.listConnections":                             CypherProcedureMetadataDbmsListConnections,
	"dbms.procedures":                                  CypherProcedureMetadataDbmsProcedures,
	"gds.fastRP.stats":                                 CypherProcedureMetadataGdsFastRPStats,
	"gds.fastRP.stream":                                CypherProcedureMetadataGdsFastRPStream,
	"gds.graph.drop":                                   CypherProcedureMetadataGdsGraphDrop,
	"gds.graph.list":                                   CypherProcedureMetadataGdsGraphList,
	"gds.graph.project":                                CypherProcedureMetadataGdsGraphProject,
	"gds.linkPrediction.adamicAdar.stream":             CypherProcedureMetadataGdsLinkPredictionAdamicAdarStream,
	"gds.linkPrediction.commonNeighbors.stream":        CypherProcedureMetadataGdsLinkPredictionCommonNeighborsStream,
	"gds.linkPrediction.jaccard.stream":                CypherProcedureMetadataGdsLinkPredictionJaccardStream,
	"gds.linkPrediction.predict.stream":                CypherProcedureMetadataGdsLinkPredictionPredictStream,
	"gds.linkPrediction.preferentialAttachment.stream": CypherProcedureMetadataGdsLinkPredictionPreferentialAttachmentStream,
	"gds.linkPrediction.resourceAllocation.stream":     CypherProcedureMetadataGdsLinkPredictionResourceAllocationStream,
	"gds.version":                                      CypherProcedureMetadataGdsVersion,
	"nornicdb.decay.info":                              CypherProcedureMetadataNornicdbDecayInfo,
	"nornicdb.knowledgepolicy.deindexStatus":           CypherProcedureMetadataNornicdbKnowledgepolicyDeindexStatus,
	"nornicdb.knowledgepolicy.info":                    CypherProcedureMetadataNornicdbKnowledgepolicyInfo,
	"nornicdb.knowledgepolicy.policies":                CypherProcedureMetadataNornicdbKnowledgepolicyPolicies,
	"nornicdb.knowledgepolicy.profiles":                CypherProcedureMetadataNornicdbKnowledgepolicyProfiles,
	"nornicdb.knowledgepolicy.resolve":                 CypherProcedureMetadataNornicdbKnowledgepolicyResolve,
	"nornicdb.stats":                                   CypherProcedureMetadataNornicdbStats,
	"nornicdb.version":                                 CypherProcedureMetadataNornicdbVersion,
	"tx.setMetaData":                                   CypherProcedureMetadataTxSetMetaData,
}

// CypherProcedureMetadata returns typed metadata for a core built-in procedure.
func CypherProcedureMetadata(name string) Message {
	constructor, ok := cypherProcedureMetadata[name]
	if !ok {
		return Message{}
	}
	return constructor()
}
