// Command proceduremetadata generates typed core procedure metadata and catalogs.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

type entry struct {
	Name string `yaml:"name"`
	EN   string `yaml:"en"`
	ES   string `yaml:"es"`
}

func main() {
	rootFlag := flag.String("root", ".", "repository root")
	flag.Parse()
	root, err := filepath.Abs(*rootFlag)
	fatalIf(err)

	entries := loadEntries(filepath.Join(root, "pkg/localization/procedure_metadata.yaml"))
	registryPath := filepath.Join(root, "pkg/cypher/procedure_registry_builtin.go")
	rewriteRegistry(registryPath, entries)
	writeMessages(filepath.Join(root, "pkg/localization/messages_cypher_procedure_metadata.go"), entries)
	writeCatalog(filepath.Join(root, "pkg/localization/catalog/active.cypherproceduremetadata.en-US.yaml"), entries, "en-US")
	writeCatalog(filepath.Join(root, "pkg/localization/catalog/active.cypherproceduremetadata.es-ES.yaml"), entries, "es-ES")
	writeCatalog(filepath.Join(root, "pkg/localization/catalog/active.cypherproceduremetadata.en-XA.yaml"), entries, "en-XA")
}

func loadEntries(path string) []entry {
	data, err := os.ReadFile(path)
	fatalIf(err)
	var entries []entry
	fatalIf(yaml.Unmarshal(data, &entries))
	if len(entries) == 0 {
		fatalf("metadata source is empty")
	}
	seen := make(map[string]struct{}, len(entries))
	for _, item := range entries {
		if item.Name == "" || item.EN == "" || item.ES == "" {
			fatalf("metadata entries require name, en, and es values")
		}
		if strings.HasPrefix(strings.ToLower(item.Name), "apoc.") {
			fatalf("APOC procedure %s must not be localized here", item.Name)
		}
		if _, exists := seen[item.Name]; exists {
			fatalf("duplicate procedure %s", item.Name)
		}
		seen[item.Name] = struct{}{}
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].Name < entries[j].Name })
	return entries
}

func rewriteRegistry(path string, entries []entry) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	fatalIf(err)
	metadata := make(map[string]struct{}, len(entries))
	for _, item := range entries {
		metadata[item.Name] = struct{}{}
	}
	found := make(map[string]struct{}, len(entries))
	ast.Inspect(file, func(node ast.Node) bool {
		call, ok := node.(*ast.CallExpr)
		if !ok || len(call.Args) < 3 {
			return true
		}
		function, ok := call.Fun.(*ast.Ident)
		if !ok || function.Name != "registerBuiltInProcedure" {
			return true
		}
		literal, ok := call.Args[0].(*ast.BasicLit)
		if !ok || literal.Kind != token.STRING {
			fatalf("built-in procedure name must be a string literal")
		}
		name, err := strconv.Unquote(literal.Value)
		fatalIf(err)
		if strings.HasPrefix(strings.ToLower(name), "apoc.") {
			if _, literalDescription := call.Args[2].(*ast.BasicLit); !literalDescription {
				fatalf("APOC procedure %s must retain a literal description", name)
			}
			function.Name = "registerBuiltInProcedureLiteral"
			return true
		}
		if _, exists := metadata[name]; !exists {
			fatalf("non-APOC procedure %s is missing metadata", name)
		}
		found[name] = struct{}{}
		function.Name = "registerBuiltInProcedure"
		call.Args[2] = &ast.CallExpr{
			Fun:  &ast.SelectorExpr{X: ast.NewIdent("localization"), Sel: ast.NewIdent("CypherProcedureMetadata")},
			Args: []ast.Expr{&ast.BasicLit{Kind: token.STRING, Value: strconv.Quote(name)}},
		}
		return true
	})
	if len(found) != len(entries) {
		for _, item := range entries {
			if _, exists := found[item.Name]; !exists {
				fatalf("metadata procedure %s has no registration", item.Name)
			}
		}
	}
	var output bytes.Buffer
	fatalIf(format.Node(&output, fset, file))
	fatalIf(os.WriteFile(path, output.Bytes(), 0o644))
}

func writeMessages(path string, entries []entry) {
	var output bytes.Buffer
	output.WriteString("// Code generated by pkg/localization/internal/proceduremetadata; DO NOT EDIT.\n\npackage localization\n\nconst (\n")
	for _, item := range entries {
		fmt.Fprintf(&output, "\tMessageCypherProcedureMetadata%s MessageID = %q\n", identifier(item.Name), messageID(item.Name))
	}
	output.WriteString(")\n\n")
	for _, item := range entries {
		name := identifier(item.Name)
		fmt.Fprintf(&output, "// CypherProcedureMetadata%s describes %s in procedure listings.\n", name, item.Name)
		fmt.Fprintf(&output, "func CypherProcedureMetadata%s() Message {\n\treturn Message{ID: MessageCypherProcedureMetadata%s, Fallback: %q}\n}\n\n", name, name, item.EN)
	}
	output.WriteString("var cypherProcedureMetadata = map[string]func() Message{\n")
	for _, item := range entries {
		fmt.Fprintf(&output, "\t%q: CypherProcedureMetadata%s,\n", item.Name, identifier(item.Name))
	}
	output.WriteString("}\n\n// CypherProcedureMetadata returns typed metadata for a core built-in procedure.\nfunc CypherProcedureMetadata(name string) Message {\n\tconstructor, ok := cypherProcedureMetadata[name]\n\tif !ok {\n\t\treturn Message{}\n\t}\n\treturn constructor()\n}\n")
	formatted, err := format.Source(output.Bytes())
	fatalIf(err)
	fatalIf(os.WriteFile(path, formatted, 0o644))
}

func writeCatalog(path string, entries []entry, locale string) {
	var output bytes.Buffer
	for _, item := range entries {
		text := item.EN
		if locale == "es-ES" {
			text = item.ES
		} else if locale == "en-XA" {
			text = "[!! " + item.EN + " !!]"
		}
		fmt.Fprintf(&output, "- id: %s\n  other: %s\n", messageID(item.Name), strconv.Quote(text))
	}
	fatalIf(os.WriteFile(path, output.Bytes(), 0o644))
}

func messageID(name string) string {
	return "cypherproceduremetadata." + strings.NewReplacer(".", "_", "-", "_").Replace(strings.ToLower(name))
}

func identifier(name string) string {
	var output strings.Builder
	capitalize := true
	for _, character := range name {
		if !unicode.IsLetter(character) && !unicode.IsDigit(character) {
			capitalize = true
			continue
		}
		if capitalize {
			character = unicode.ToUpper(character)
			capitalize = false
		}
		output.WriteRune(character)
	}
	return output.String()
}

func fatalIf(err error) {
	if err != nil {
		fatalf("%v", err)
	}
}

func fatalf(format string, arguments ...any) {
	fmt.Fprintf(os.Stderr, "proceduremetadata: "+format+"\n", arguments...)
	os.Exit(1)
}
