#!/usr/bin/env python3
"""Generate pkg/cypher/temporal_zone_names.go from a Neo4j 2026.x server.

Neo4j's format() and temporal pattern constructors print and read time-zone
names with Java's English (CLDR) zone names: z / zzzz (specific, standard or
daylight) and v / vvvv (generic). This script asks the server for every zone
the Python tz database knows, in January and July, and which zone each name
parses to, and writes them as Go tables.

    pip install neo4j tzdata
    python3 scripts/gen_temporal_zone_names.py bolt://localhost:7687 > pkg/cypher/temporal_zone_names.go
    gofmt -w pkg/cypher/temporal_zone_names.go
"""
import sys
import zoneinfo
from datetime import datetime

from neo4j import GraphDatabase


def gmt_name(seconds):
    """Java's long localized offset (OOOO): GMT, GMT+01:00, GMT-05:30."""
    if seconds == 0:
        return "GMT"
    sign = "+" if seconds > 0 else "-"
    seconds = abs(seconds)
    return f"GMT{sign}{seconds // 3600:02d}:{seconds % 3600 // 60:02d}"


def go_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main(uri):
    driver = GraphDatabase.driver(uri, auth=None)
    zones = {}
    with driver.session() as session:
        for zone in sorted(zoneinfo.available_timezones()):
            names = {}
            try:
                for month in (1, 7):
                    record = session.run(
                        "CYPHER 25 WITH datetime({year: 2026, month: $m, day: 15, hour: 12, timezone: $z}) AS d "
                        "RETURN format(d, 'z|zzzz|v|vvvv') AS v, d.offsetSeconds AS o", {"m": month, "z": zone}).single()
                    short, long_, generic_short, generic_long = record["v"].split("|")
                    fallback = gmt_name(record["o"])
                    short = "" if short == fallback else short
                    long_ = "" if long_ == fallback else long_
                    generic_short = "" if generic_short == fallback else generic_short
                    generic_long = "" if generic_long == fallback else generic_long
                    daylight = bool(zoneinfo.ZoneInfo(zone).dst(datetime(2026, month, 15, 12)))
                    names["dst" if daylight else "std"] = (short, long_, generic_short, generic_long)
            except Exception:  # noqa: BLE001 - a zone the server doesn't know
                continue
            zones[zone] = names
        parse = {"short": {}, "long": {}}
        candidates = {"short": set(), "long": set()}
        for names in zones.values():
            for short, long_, generic_short, generic_long in names.values():
                candidates["short"].update(n for n in (short, generic_short) if n)
                candidates["long"].update(n for n in (long_, generic_long) if n)
        for style, pattern in (("short", "z"), ("long", "zzzz")):
            for name in sorted(candidates[style]):
                if name.startswith(("GMT", "UTC")):
                    continue  # GMT+01:00 parses as an offset zone
                try:
                    record = session.run("CYPHER 25 RETURN datetime($t, $p).timezone AS z",
                                         {"t": "2026-01-15 12:00 " + name, "p": "yyyy-MM-dd HH:mm " + pattern}).single()
                    parse[style][name] = record["z"]
                except Exception:  # noqa: BLE001 - a name Java doesn't read back
                    continue
    driver.close()

    out = ["// Code generated by scripts/gen_temporal_zone_names.py from Neo4j 2026.09; DO NOT EDIT.", "",
           "package cypher", "",
           "// javaZoneNames are Java's English names of each time zone, as Neo4j's",
           "// format() prints them: standard and daylight specific names (z, zzzz) and",
           "// the generic names (v, vvvv). An empty name is the zone's offset as",
           "// GMT+hh:mm, Java's fallback.",
           "var javaZoneNames = map[string]javaZoneNameSet{"]
    for zone in sorted(zones):
        names = zones[zone]
        std = names.get("std") or names.get("dst")
        dst = names.get("dst") or std
        fields = [std[0], dst[0], std[1], dst[1], std[2], std[3]]
        out.append(f"\t{go_string(zone)}: {{{', '.join(go_string(f) for f in fields)}}},")
    out.append("}")
    for style, comment in (("short", "z or v"), ("long", "zzzz or vvvv")):
        out += ["", f"// javaZone{style.capitalize()}NameZones are the zones the names a {comment} pattern",
                "// letter reads stand for, as Java resolves them.",
                f"var javaZone{style.capitalize()}NameZones = map[string]string{{"]
        for name in sorted(parse[style]):
            out.append(f"\t{go_string(name)}: {go_string(parse[style][name])},")
        out.append("}")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "bolt://localhost:7687")
