// Package differential runs Cypher corpora against NornicDB and the pinned
// Neo4j and ratchets the statements whose answers differ (#754).
//
// Two corpora are compared, through every route a client uses (Bolt
// auto-commit, a Bolt explicit transaction, HTTP /tx/commit):
//   - the sweep (testdata/differential/sweep.json.gz, generated by
//     scripts/cypher-tck/differential/gen_sweep.py): statements for every
//     operator and clause family on one small graph (#907);
//   - the issue reproductions (testdata/differential/issues.json, extracted by
//     scripts/cypher-tck/differential/extract_issue_corpus.py): the Cypher in
//     the issue texts, run in each issue's order on an empty graph.
//
// The known differences are listed in testdata/differential/known_mismatches.jsonl,
// one per statement and route, each with the issue that tracks it. A run fails
// when a statement that matched starts to differ, and reports the listed
// statements that now match so the list can be trimmed in the same change.
package differential

import (
	"compress/gzip"
	"encoding/json"
	"fmt"
	"os"
)

// SweepCorpus is the generated sweep: Setup creates the graph every case
// reads.
type SweepCorpus struct {
	Setup []string    `json:"setup"`
	Cases []SweepCase `json:"cases"`
}

// SweepCase is one generated statement. A Rollback case writes: the graph is
// restored after it.
type SweepCase struct {
	ID       string `json:"id"`
	Family   string `json:"family"`
	Position string `json:"position"`
	Query    string `json:"query"`
	Rollback bool   `json:"rollback"`
}

// IssueCase is the Cypher of one issue's text, in the issue's order.
type IssueCase struct {
	Issue      int              `json:"issue"`
	Title      string           `json:"title"`
	Statements []IssueStatement `json:"statements"`
}

// IssueStatement is one statement of an issue.
type IssueStatement struct {
	ID    string `json:"id"`
	Query string `json:"query"`
}

// SweepIssue is the issue that tracks the sweep's differences.
const SweepIssue = 907

// LoadSweep reads the gzipped sweep corpus at path.
func LoadSweep(path string) (SweepCorpus, error) {
	var corpus SweepCorpus
	file, err := os.Open(path)
	if err != nil {
		return corpus, err
	}
	defer file.Close()
	reader, err := gzip.NewReader(file)
	if err != nil {
		return corpus, fmt.Errorf("read %s: %w", path, err)
	}
	defer reader.Close()
	if err := json.NewDecoder(reader).Decode(&corpus); err != nil {
		return corpus, fmt.Errorf("decode %s: %w", path, err)
	}
	if len(corpus.Cases) == 0 {
		return corpus, fmt.Errorf("%s has no cases", path)
	}
	return corpus, nil
}

// LoadIssues reads the issue-reproduction corpus at path.
func LoadIssues(path string) ([]IssueCase, error) {
	content, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var corpus []IssueCase
	if err := json.Unmarshal(content, &corpus); err != nil {
		return nil, fmt.Errorf("decode %s: %w", path, err)
	}
	if len(corpus) == 0 {
		return nil, fmt.Errorf("%s has no issues", path)
	}
	return corpus, nil
}
